megautils.runFile("entities/main/barhandler.lua")
megautils.runFile("entities/main/megaman.lua")
megautils.runFile("entities/main/pickups.lua")
megautils.runFile("entities/main/pause.lua")
megautils.runFile("entities/main/weapons.lua")
megautils.runFile("entities/main/ready.lua")

megautils.runFile("entities/mechanics/solid.lua")
megautils.runFile("entities/mechanics/death.lua")
megautils.runFile("entities/mechanics/ladder.lua")
megautils.runFile("entities/mechanics/checkpoint.lua")
megautils.runFile("entities/mechanics/bossdoor.lua")

megautils.runFile("entities/misc/spawner.lua")
megautils.runFile("entities/misc/camera.lua")
megautils.runFile("entities/misc/trigger.lua")
megautils.runFile("entities/misc/fade.lua")
megautils.runFile("entities/misc/timer.lua")
megautils.runFile("entities/misc/miscparticles.lua")
megautils.runFile("entities/misc/transitions.lua")
megautils.runFile("entities/misc/parallax.lua")