class = require("core/classic")
inspect = require("core/inspect")
tween = require("core/tween")
anim8 = require("core/anim8")
require("core/view")
sti = require("core/sti")
require("core/base64")
require("core/input")
require("core/megautils")
json = require("core/json")
require("core/utils")
require("core/control")
require("core/save")
cscreen = require("core/cscreen")
require("core/boundbox")
require("core/audio")
require("core/loader")
require("core/gamestates")
require("core/entitysystem")
require("core/console")
require("core/commands")
require("entities/requireobjects")
