lualzw = require("core/lualzw")
binser = require("core/binser")
local x2l = require("core/xml2lua")
xml2lua = x2l.parser(require("core/xmlhandler/tree"))
class = require("core/classic")
inspect = require("core/inspect")
require("core/image")
require("core/tween")
require("core/anim8")
require("core/quad")
require("core/animationset")
require("core/view")
cartographer = require("core/cartographer")
require("core/input")
require("core/megautils")
require("core/utils")
require("core/control")
require("core/save")
cscreen = require("core/cscreen")
require("core/boundbox")
require("core/audio")
require("core/loader")
require("core/gamestates")
require("core/entitysystem")
require("core/collision")
require("core/console")