lualzw = love.filesystem.load("core/lualzw.lua")()
class = love.filesystem.load("core/classic.lua")()
inspect = love.filesystem.load("core/inspect.lua")()
tween = love.filesystem.load("core/tween.lua")()
anim8 = love.filesystem.load("core/anim8.lua")()
love.filesystem.load("core/quad.lua")()
love.filesystem.load("core/animationset.lua")()
love.filesystem.load("core/view.lua")()
cartographer = love.filesystem.load("core/cartographer.lua")()
love.filesystem.load("core/input.lua")()
love.filesystem.load("core/megautils.lua")()
binser = love.filesystem.load("core/binser.lua")()
local x2l = love.filesystem.load("core/xml2lua.lua")()
xml2lua = x2l.parser(love.filesystem.load("core/xmlhandler/tree.lua")())
love.filesystem.load("core/utils.lua")()
love.filesystem.load("core/control.lua")()
love.filesystem.load("core/save.lua")()
cscreen = love.filesystem.load("core/cscreen.lua")()
love.filesystem.load("core/boundbox.lua")()
love.filesystem.load("core/audio.lua")()
love.filesystem.load("core/loader.lua")()
love.filesystem.load("core/gamestates.lua")()
love.filesystem.load("core/entitysystem.lua")()
love.filesystem.load("core/collision.lua")()
love.filesystem.load("core/console.lua")()